// Code generated by "stringer -type=Register"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IPRegister-0]
	_ = x[SPRegister-1]
	_ = x[ARegister-2]
	_ = x[BRegister-3]
	_ = x[CRegister-4]
	_ = x[DRegister-5]
	_ = x[ERegister-6]
	_ = x[FRegister-7]
}

const _Register_name = "IPRegisterSPRegisterARegisterBRegisterCRegisterDRegisterERegisterFRegister"

var _Register_index = [...]uint8{0, 10, 20, 29, 38, 47, 56, 65, 74}

func (i Register) String() string {
	if i >= Register(len(_Register_index)-1) {
		return "Register(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Register_name[_Register_index[i]:_Register_index[i+1]]
}
