// Code generated by "stringer -type=Register"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IP-0]
	_ = x[SP-1]
	_ = x[A-2]
	_ = x[B-3]
	_ = x[C-4]
	_ = x[D-5]
	_ = x[E-6]
	_ = x[F-7]
}

const _Register_name = "IPSPABCDEF"

var _Register_index = [...]uint8{0, 2, 4, 5, 6, 7, 8, 9, 10}

func (i Register) String() string {
	if i >= Register(len(_Register_index)-1) {
		return "Register(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Register_name[_Register_index[i]:_Register_index[i+1]]
}
